var currX = -2;  // Starting at '5', which is 2,0
var currY = 0;
var combo = "";

//var arrDir = [
//    'ULL'
//    , 'RRDDD'
//    , 'LURDL'
//    , 'UUUUD'
//];

var arrDir = [
    'LRRLLLRDRURUDLRDDURULRULLDLRRLRLDULUDDDDLLRRLDUUDULDRURRLDULRRULDLRDUDLRLLLULDUURRRRURURULURRULRURDLULURDRDURDRLRRUUDRULLLLLDRULDDLLRDLURRLDUURDLRLUDLDUDLURLRLDRLUDUULRRRUUULLRDURUDRUDRDRLLDLDDDLDLRRULDUUDULRUDDRLLURDDRLDDUDLLLLULRDDUDDUUULRULUULRLLDULUDLLLLURRLDLUDLDDLDRLRRDRDUDDDLLLLLRRLLRLUDLULLDLDDRRUDDRLRDDURRDULLLURLRDLRRLRDLDURLDDULLLDRRURDULUDUDLLLDDDLLRLDDDLLRRLLURUULULDDDUDULUUURRUUDLDULULDRDDLURURDLDLULDUDUDDDDD'
    , 'RUURUDRDUULRDDLRLLLULLDDUDRDURDLRUULLLLUDUDRRUDUULRRUUDDURDDDLLLLRRUURULULLUDDLRDUDULRURRDRDLDLDUULUULUDDLUDRLULRUDRDDDLRRUUDRRLULUULDULDDLRLURDRLURRRRULDDRLDLLLRULLDURRLUDULDRDUDRLRLULRURDDRLUDLRURDDRDULUDLDLLLDRLRUDLLLLLDUDRDUURUDDUDLDLDUDLLDLRRDLULLURLDDUDDRDUDLDDUULDRLURRDLDLLUUDLDLURRLDRDDLLDLRLULUDRDLLLDRLRLLLDRUULUDLLURDLLUURUDURDDRDRDDUDDRRLLUULRRDRULRURRULLDDDUDULDDRULRLDURLUDULDLDDDLRULLULULUDLDDRDLRDRDLDULRRLRLRLLLLLDDDRDDULRDULRRLDLUDDDDLUDRLLDLURDLRDLDRDRDURRDUDULLLDLUDLDRLRRDDDRRLRLLULDRLRLLLLDUUURDLLULLUDDRLULRDLDLDURRRUURDUDRDLLLLLLDDDURLDULDRLLDUDRULRRDLDUDRLLUUUDULURRUR'
    , 'URRRLRLLDDDRRLDLDLUDRDRDLDUDDDLDRRDRLDULRRDRRDUDRRUUDUUUDLLUURLRDRRURRRRUDRLLLLRRDULRDDRUDLRLUDURRLRLDDRRLUULURLURURUDRULDUUDLULUURRRDDLRDLUDRDLDDDLRUDURRLLRDDRDRLRLLRLRUUDRRLDLUDRURUULDUURDRUULDLLDRDLRDUUDLRLRRLUDRRUULRDDRDLDDULRRRURLRDDRLLLRDRLURDLDRUULDRRRLURURUUUULULRURULRLDDDDLULRLRULDUDDULRUULRRRRRLRLRUDDURLDRRDDULLUULLDLUDDDUURLRRLDULUUDDULDDUULLLRUDLLLRDDDLUUURLDUDRLLLDRRLDDLUDLLDLRRRLDDRUULULUURDDLUR'
    , 'UULDRLUULURDRLDULURLUDULDRRDULULUDLLDURRRURDRLRLLRLDDLURRDLUUDLULRDULDRDLULULULDDLURULLULUDDRRULULULRDULRUURRRUDLRLURDRURDRRUDLDDUURDUUDLULDUDDLUUURURLRRDLULURDURRRURURDUURDRRURRDDULRULRRDRRDRUUUUULRLUUUDUUULLRRDRDULRDDULDRRULRLDLLULUUULUUDRDUUUDLLULDDRRDULUURRDUULLUUDRLLDUDLLLURURLUDDLRURRDRLDDURLDLLUURLDUURULLLRURURLULLLUURUUULLDLRDLUDDRRDDUUDLRURDDDRURUURURRRDLUDRLUULDUDLRUUDRLDRRDLDLDLRUDDDDRRDLDDDLLDLULLRUDDUDDDLDDUURLDUDLRDRURULDULULUDRRDLLRURDULDDRRDLUURUUULULRURDUUDLULLURUDDRLDDUDURRDURRUURLDLLDDUUDLLUURDRULLRRUUURRLLDRRDLURRURDULDDDDRDD'
    , 'LLRUDRUUDUDLRDRDRRLRDRRUDRDURURRLDDDDLRDURDLRRUDRLLRDDUULRULURRRLRULDUURLRURLRLDUDLLDULULDUUURLRURUDDDDRDDLLURDLDRRUDRLDULLRULULLRURRLLURDLLLRRRRDRULRUDUDUDULUURUUURDDLDRDRUUURLDRULDUDULRLRLULLDURRRRURRRDRULULUDLULDDRLRRULLDURUDDUULRUUURDRRLULRRDLDUDURUUUUUURRUUULURDUUDLLUURDLULUDDLUUULLDURLDRRDDLRRRDRLLDRRLUDRLLLDRUULDUDRDDRDRRRLUDUDRRRLDRLRURDLRULRDUUDRRLLRLUUUUURRURLURDRRUURDRRLULUDULRLLURDLLULDDDLRDULLLUDRLURDDLRURLLRDRDULULDDRDDLDDRUUURDUUUDURRLRDUDLRRLRRRDUULDRDUDRLDLRULDL'

             ];

for (var i = 0; i < arrDir.length; i++) {
    var thisDirStr = arrDir[i];
    
    for (var j = 0; j < thisDirStr.length; j++) {
        var thisDir = thisDirStr.charAt(j);
        
        process.stdout.write(thisDir + ": ");
        if (thisDir === 'L' && (currY !== -2 && currY !== 2) && (currX > -1 || (currX === -1 && currY === 0))) { currX--; console.log ("L: (" + currX + "," + currY + ")"); }
        else if (thisDir === 'R' && (currY !== -2 && currY !== 2) && (currX < 1 || (currX === 1 && currY === 0))) { currX++; console.log ("R: (" + currX + "," + currY + ")"); }
        else if (thisDir === 'U' && (currX !== -2 && currX !== 2) && (currY < 1 || (currX === 0 && currY === 1))) { currY++; console.log ("U: (" + currX + "," + currY + ")"); }
        else if (thisDir === 'D' && (currX !== -2 && currX !== 2) && (currY > -1 || (currX === 0 && currY === -1))) { currY--; console.log ("D: (" + currX + "," + currY + ")"); }
        else console.log("N: (" + currX + "," + currY + ")");
    }
    
    if (currX === 0 && currY === 2) combo += "1";
    else if (currX === -1 && currY === 1) combo += "2";
    else if (currX === 0 && currY === 1) combo += "3";
    else if (currX === 1 && currY === 1) combo += "4";
    else if (currX === -2 && currY === 0) combo += "5";
    else if (currX === -1 && currY === 0) combo += "6";
    else if (currX === 0 && currY === 0) combo += "7";
    else if (currX === 1 && currY === 0) combo += "8";
    else if (currX === 2 && currY === 0) combo += "9";
    else if (currX === -1 && currY === -1) combo += "A";
    else if (currX === 0 && currY === -1) combo += "B";
    else if (currX === 1 && currY === -1) combo += "C";
    else if (currX === 0 && currY === -2) combo += "D";
    
    console.log("COMBO[" + i + "]: " + combo);
}